
#服务集群，模块二

server:
  port: 8082

spring:
  application:
    name: ann-payment   #配置服务模块集群时，集群内模块应用名称要一样
  #配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 8989909

#MyBatis配置
mybatis:
  #mapper-locations: classpath:mapper/*.xml  #设定MyBatis映射文件的扫描路径
  mapperLocations: classpath*:mapper/**/*Mapper.xml  # 映射文件的扫描路径，也可以设定多重路径
  type-aliases-package: com.springcloud.learn.entity   #设定实体类别名所使用的包，以后不用再xxxMapper.xml里写实体类全路径了

#设置sql日志打印
logging:
  level:
    com.springcloud.learn.mapper: debug

#Eureka配置
eureka:
  client:
    #这里写成fetchRegistry也可以
    fetch-registry: true    #设置是否从EurekaServer抓取自己的注册信息，默认为true，单节点怎么设置无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true     #默认是true,表示将自己注册进EurekaServer，这样Eureka的服务注册中心就可以显示本服务模块，并进行管理
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #注意地址格式不要写错，最好复制，否则无法注册成功
  #这里不设置自定义名称，不显示 ipd地址，为了和 ann-payment-8081做对比
  #instance:
    #instance-id: ann-payment-8082   #在Eureka管理页面显示此名称，不显示默认的带电脑名字的名称
    #prefer-ip-address: true     #设置把鼠标放到服务模块时，显示服务ip地址，不是默认的actuator/..，当然也可以访问

