server:
  port: 83

#配置服务名称
spring:
  application:
    name: ian-consumer-hystrix-83

#配置Eureka
eureka:
  client:
    fetch-registry: true  #设置是否从EurekaServer抓取自己的注册信息，默认为true，单节点怎么设置无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true  #默认是true,表示将自己注册进EurekaServer，这样Eureka的服务注册中心就可以显示本服务模块，并进行管理
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #注意地址格式不要写错，最好复制，否则无法注册成功
    #设置在Eureka注册中心显示的服务名称
  instance:
    instance-id: ian-consumer-hystrix-83
    prefer-ip-address: true  #设置把鼠标放到服务模块时，显示服务ip地址，不是默认的actuator/..，

#设置开启Feign使用Hystrix
feign:
  hystrix:
    enabled: true
