server:
  port: 8081



spring:
  application:
    name: cloud-alibaba-payment   #支付模块集群，服务名要同一，注册到Nacos的就是这个名字，跟注册到Eureka一样。设置好后，在Nacos服务管理页面会显示集群的实例数量。
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #注册本模块服务到Nacos服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #这里加“http://”报错，无法注册到Nacos，原因待查。Nacos的默认端口号是8848，可在其配置文件application.properties里修改

#MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml   #设置映射文件的路径
  type-aliases-package: com.springcloud.learn.entity   #设定实体类别名所使用的包，以后不用再xxxMapper.xml里写实体类全路径了


#设置打印sql日志
logging:
  level:
    com.springcloud.learn.mapper: debug





