

#服务集群，模块一
#集群中的模块提供的功能相同

server:
  port: 8081

spring:
  application:
    name: ann-payment    #1，配置服务模块集群时，集群内模块应用名称要一样，从消费者模块访问集群时就使用该名称，例如http://ann-payment/get/3；
                         #2，注意只有注册到Eureka的模块才可以使用域名调用，外部如果在浏览器地址栏直接输入无法调用；

  #配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    password: 8989909
#MyBatis配置
mybatis:
  #mapper-locations: classpath:mapper/*.xml  #设定MyBatis映射文件的扫描路径
  mapperLocations: classpath*:mapper/**/*Mapper.xml  # 映射文件的扫描路径，也可以设定多重路径
  type-aliases-package: com.springcloud.learn.entity   #设定实体类别名所使用的包，以后不用再xxxMapper.xml里写实体类全路径了

#设置sql日志打印
logging:
  level:
    com.springcloud.learn.mapper: debug

#Eureka配置
eureka:
  client:
    #这里写成fetchRegistry也可以
    fetch-registry: true    #设置是否从EurekaServer抓取自己的注册信息，默认为true，单节点怎么设置无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true     #默认是true,表示将自己注册进EurekaServer，这样Eureka的服务注册中心就可以显示本服务模块，并进行管理
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #注意地址格式不要写错，最好复制，否则无法注册成功
  instance:
    instance-id: ann-payment-8081   #在Eureka管理页面显示此名称，不显示默认的带电脑名字的名称
    prefer-ip-address: true     #设置把鼠标放到服务模块时，显示服务ip地址，不是默认的actuator/..，当然也可以访问

    #设置取消Eureka自我保护机制，client端进行如下设置，Eureka端也要进行相应设置
    #设置客户端client（本模块）向Eureka注册中心发送心跳信息的间隔，单位为秒，默认30秒
#    lease-renewal-interval-in-seconds: 2
    #设置Eureka Server（）在收到最后一次的心跳信息后等待的上线时间（默认是90s），这里必须大于上面的时间，否则设置无意义
#    lease-expiration-duration-in-seconds: 5


