server:
  port: 6600
spring:
  application:
    name: cloud-config-server-6600
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/plms/spring-cloud.git   #SpringCloud配置中心仓库地址
          force-pull: true
          search-paths:
            - SpringCloud/config-center    #仓库名
      label: master  #要读取的分支名


#Eureka配置，把配置总中心注册进Eureka
eureka:
  client:
    fetch-registry: true  #设置是否从EurekaServer抓取自己的注册信息，默认为true，单节点怎么设置无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true  #默认是true,表示将自己注册进EurekaServer，这样Eureka的服务注册中心就可以显示本服务模块，并进行管理
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #注意地址格式不要写错，最好复制，否则无法注册成功


