
#本配置文件中“routes”参数为动态路由设置范例

#设置模块参数
spring:
  application:
    name: spring-cloud-gateway-9001
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由功能，即从注册中心获取统一的服务名进行访问，例"ann-payment"，而不是"localhost:8081"这样，
      routes:   #这里设置网关的路由转发，routes为复数，代表可设置多个路由，根据匹配规则转发到不同的服务。
        - id: ann-payment-routh01   #网关代理的路由的id，名称自定义，必须唯一，建议设置和服务模块名相关。
          uri: lb://FRANK-CONSUMER-FEIGN-81    #设置访问动态的路由，即直接访问服务在Eureka中注册的名称，注意参数值的写法，加”lb://“load balance
          predicates:
            - Path=/feign-consumer/get/**   #配置访问consumer-feign-81的路径
            #断言还可以设置其它参数，可参Spring Cloud Gateway照官方文档。
            - After=2022-07-26T20:35:18.630+08:00[Asia/Shanghai]   #此处设置只有在规定时间之后才可访问此路径Path，在此之前则报错。注意时间格式，查看在GatewayTest.java中的获取方式
            - Cookie=userName,Tom   #此处表示当访问的请求中的Cookie中含有键值对userName=Tom时才会放行，命令行请求的写法：curl http://localhost:9001/feign-consumer/get/1 --cookie "userName=Tom"，见本章节Gateway笔记
            - Header=X-Request-Id, \d+  #表示请求头中必须有X-Request-Id属性并且其值必须大于0，命令行请求的写法；curl http://localhost:9001/feign-consumer/get/1 --cookie "userName=Tom" -H "X-Request-Id:10"
            #...... 其它请求参数参照SpringCloud官方文档
        - id: ann-payment-routh02
          uri: lb://HANS-CONSUMER-HYSTRIX-82
          predicates:
            - Path=/hystrix/consumer/get/**


#配置Eureka,网关也要注册到Eureka注册中心里去
eureka:
  client:
    fetch-registry: true  #设置是否从EurekaServer抓取自己的注册信息，默认为true，单节点怎么设置无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true  #默认是true,表示将自己注册进EurekaServer，这样Eureka的服务注册中心就可以显示本服务模块，并进行管理
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #注意地址格式不要写错，最好复制，否则无法注册成功
    #设置在Eureka注册中心显示的服务名称
  instance:
    instance-id: spring-cloud-gateway-9001
    prefer-ip-address: true  #设置把鼠标放到服务模块时，显示服务ip地址，不是默认的actuator/..，




